baseURL = 'https://frczero.org/'
languageCode = 'en-us'
title = 'FRC Zero'

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
